### PR TITLE
dirtbit's contribution on 3D Model

### PR DESCRIPTION
**Pull request by dirtbit**
Hi @earms

Have made some changes I found useful to the OpenTrickler 3D Model:

* Display Assy Enclosure + required Trickler Adapter Plate
* Pico Expansion Board enclosure + required OpenTrickler_RearBody
* Volume Reduction Inserts for easy cleaning

Put it into a "CommunityContribution" folder, including readme.md depicting overview, print orientation as well as print information and required screws/nuts description.

Unfortunately I'm too dump to make such a nice 3D Model as you did.
Furthermore, I'm not a big fan of this brass inserts, so I converted the entire OpenTrickler into M3 nuts, you'll notice on the OpenTrickler_RearBody :-)

Feel free to include this into your repo, or maybe it inspires you for an even nicer solution ;-)

### CODE REVIEW

**Comment by eamars** [comment]
Thanks for the awesome work!

Below are my comments: 
1. Are you able to pre-orientate the printed part to the ready-to-print  position? It could be done by using the 3D builder from the Windows Store, developped by Microsoft. 
2. You might need the cross pattern to print the hex nut without support. I can show some example later. 
3. The trickler rear body is based on the older design. You may need to up-rev to v1.1 with bearing cover. 
4. The trickler rear body should be print lying down. Otherwise you may have trouble inserting bearing.
5. You may need to highlight the supported mini 12864 display. Different manufactor may have different spec thus I don't want to create confusion.

**Comment by dirtbit** [comment]
OK, here we go:

1. agree, done
2. to make it really perfect, yes. In real-life, it works this way as well. Nevertheless, I'm interested on how you do this.
3. It is already v1.1, the groove for the bearing cover is removed as I don't need this with the inserts
4. agree, done
5. agree, done in readme.md

**Comment by eamars** [comment]
Example with trickler adapter plate:
Without the cross pattern, the first layer of the cylinder is printing mid-air. 
image

With the cross pattern 
layer 1
image

layer2
image

layer 3
image

layer 4
image

This way the slicer will always generate the bridge that connects to the wall instead of mid-air. 


The trick is to draw 4 lines that tangent to the center hole, and connect/cross the edge. 
image

Then extrude 0.4mm on two of four sides, and 0.2mm on the other two. 
image


Of course you will need to re-calculate the depth of the cut out to compensate for additional ~0.3mm of extrusion.

**Comment by dirtbit** [comment]
Hi @eamars 

Thank you very much for the explanation. I agree this is from an "artistic" standpoint a very smart solution to avoid "supports on build plate only" for printing, but at the same time looking from a mechanical standpoint I'd argue that the screws might loose tension over time - although this is just a feeling, not tested. 
The little supports pop out super easy when pushed out from backside.

I agree with all other feedback and fixed those and consider this now as done ;-)

**Pull request merged**
