### PR TITLE
Some enhancements to share

### PR DESCRIPTION
**Pull request by 4numen**

### CODE REVIEW

**Comment by eamars** [comment]
Do you mind sharing the STEP file as well? This will help if others want to make modifications to the design. 

Also, I reckon 3mf and stls are somehow equivalent, I don't think you will need both copies.

**Comment by 4numen** [comment]
Don't mind at all, just need to play with f360 to export just these files
in step instead of whole jj100b shield design.

pon., 8 kwi 2024, 00:59 użytkownik Ran Bao ***@***.***>
napisał:

**Comment by 4numen** [comment]
Should work now

**Comment by 4numen** [comment]
Added phone holder. Getting cleaner with commits - preview button in file editig does the trick ;)

**Pull request merged**
